name: SwordBuffs
version: ${project.version}
description: A plugin that gives you buffs from swords!
author: claxon007
website: https://www.evermine.it
main: it.evermine.swordbuffs.SwordBuffs

depends: [Vault]