name: SwordBuffs
version: 1.5.3-SNAPSHOT
description: Buffs sulle spade
author: claxon007
website: https://www.evermine.it
main: it.evermine.swordbuffs.SwordBuffs

commands:
  addbuff:
    usage: /<command>